state: CO

links:
- name: primary
  url: https://public.tableau.com/views/Colorado_COVID19_Data/CO_Case_Demographics?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 1400
      height: 2000
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("#tabZoneId172");
    await page.click("#tabZoneId172");
    await page.waitForDelay(1000);
    page.done();
  message: using viewport width 1400 for CO
