state: NJ

- name: primary
  url: https://covid19.nj.gov/#live-updates
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    await page.waitForSelector("button#overlay-close");
    page.click("button#overlay-close");
    await page.waitForDelay(30000);
    page.done();
  message: close the overlay

- name: secondary
  url: https://dashboards.doh.nj.gov/views/DailyConfirmedCaseSummary7_22_2020/ConfirmedCases?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 2000
  message: cases, using viewport width 2000

- name: tertiary
  url: https://dashboards.doh.nj.gov/views/ProbableDeaths_07_21/ConfirmedProbableDashboard?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 2000
  message: deaths, using viewport width 2000

- name: quaternary
  url: https://dashboards.doh.nj.gov/views/DailyConfirmedCaseSummary7_22_2020/EverHospitalized?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 2000
  message: hospitalizations, using viewport width 2000

- name: quinary
  url: https://dashboards.doh.nj.gov/views/DailyConfirmedCaseSummary7_22_2020/Deaths?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 2000
  message: deaths backup, using viewport width 2000
